=== Jayasreeirusan/Spectrum-Access-System/schema/HeartbeatRequest.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Heartbeat parameters provided by a CBSD",
  "type": "object",
  "required": [ "cbsdId", "grantId" ],
  "properties": {
    "cbsdId": { "type": "string",
                "description": "Unique designator for the CBSD as returned from the registration procedure." },
    "grantId": { "type": "string",
                 "description": "Unique designator for the grant as returned from the spectrum grant procedure." },
    "grantRenew": { "type": "boolean",
                    "description": "If set to true, the CBSD is asking for a renewal of the grant." },
    "operationState": { "enum": [ "Transmission", "Granted" ],
                        "description": "If present, represents the current state of operation of the CBSD. The CBSD should include this field if requested by the SAS in a previous operationStatusReq field in a heartbeat response." },
    "operationParam": { "$ref": "file:OperationParam.schema.json" },
    "measReport": { "$ref": "file:MeasReport.schema.json" }
  }
}

=== Jayasreeirusan/Spectrum-Access-System/schema/HeartbeatRequestExample.json
{
  "cbsdId": "sas1/cbsd1",
  "grantId": "sas1/grant1",
  "grantRenew": true,
  "operationState": "Transmission",
  "operationParam": {
     "palCredential": [ "license" ],
     "peakPower": 30,
     "operationFrequencyRange": { "lowFrequency": 3600000000, "highFrequency": 3610000000 }
  },
  "measReport": {
  }
}
