=== Jayasreeirusan/Spectrum-Access-System/schema/RegistrationRequest.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Registration parameters provided for a CBSD",
  "type": "object",
  "required": [ "cbsdCategory", "callSign", "userId", "airInterface",
                "fccId", "cbsdManufacturer", "cbsdSerialNumber", "maximumGrants",
                "sensingCapability", "installationParam" ],
  "properties": {
    "userId": { "type": "string",
                "description": "Unique user designator for the operator. Generation mechanism TBD" },
    "fccId": { "type": "string",
               "description": "The certification FCC ID for the hardware" },
    "cbsdSerialNumber": { "type": "string",
                          "description": "Unique identifier for the CBSD chosen by the manufacturer" },
    "cbsdManufacturer": { "type": "string",
                          "description": "Name of the device manufacturer" },
    "cbsdCategory": { "enum" : [ "A", "B" ],
                      "description": "A if the device is Category A; B if it is Category B" },
    "callSign": { "type": "string",
                  "description": "The call sign for the operator. Meaning and origin TBD" },
    "maximumGrants": { "type": "number",
                       "description": "Maximum number of grants which is supported by the device",
                       "minimum": 1 },
    "sensingCapability": { "type": "array",
                           "description": "List of supported sensing capabilities of the device",
                           "items": { "enum": [ "esc", "receivedInterferencePower" ],
                                      "description": "Measurement capabilities of the CBSD." }
                         },
    "airInterface": { "$ref": "file:AirInterface.schema.json" },
    "installationParam": { "$ref": "file:InstallationParam.schema.json" }
  }
}

=== Jayasreeirusan/Spectrum-Access-System/schema/RegistrationRequestExample.json
{
  "fccId": "321cba",
  "cbsdCategory": "A",
  "callSign": "KPPP",
  "userId": "John Doe",
  "airInterface": {
    "radioTechnology": "E-UTRA",
    "supportedSpec": "LTE-Rel10"
  },
  "cbsdManufacturer": "Equipment Maker C",
  "cbsdSerialNumber": "4321dcba",
  "maximumGrants": 2,
  "sensingCapability": [
    "receivedInterferencePower"
  ],
  "installationParam": {
    "latitude": 37.425056,
    "longitude": -122.084113,
    "height": 9.3,
    "indoorDeployment": false,
    "antennaAzimuth": 270.5,
    "antennaDowntiltMech": 3,
    "antennaGain": 16,
    "antennaBeamwidth": 30
  }
}
